<i18n>
{
  "en": {
    "description": "In the United States, electricity is generated in many different ways, with a wide variation in environmental impact. Electricity generation from the combustion of fossil fuels contributes toward unhealthy air quality, acid rain, and global climate change.<br><br>Many electricity customers can choose their provider of electricity or can purchase green power from their utility. In fact, you might now have the option of choosing cleaner, more environmentally-friendly sources of energy.<br><br>To compare the fuel mix (i.e., resource mix) and air emission rates of the electricity in your region to the national average and to determine the air emissions that result from electricity use in your home or business, either select the appropriate eGRID subregion or enter your ZIP code to determine the appropriate eGRID subregion.",
    "linkToEgrid": "eGRID database",
    "pointToEgrid": "Power Profiler does not provide information about the environmental attributes of electric power generated by individual companies. For company-specific information, access EPA's {0}.",
    "ariaLabels": {
      "opensNewWin": "Opens new window"
    }
  },
  "es": {
    "description": "En los Estados Unidos, la electricidad se genera de muchas formas distintas, con un impacto ambiental muy variado. La generación de energía a partir de la combustión de combustibles fósiles incide en una calidad de aire insalubre, en la lluvia ácida y en el cambio climático global.<br><br>Muchos consumidores de electricidad pueden elegir a su proveedor de electricidad o bien comprar energía ecológica a su empresa de servicios. De hecho, ahora es probable que usted tenga la opción de elegir fuentes de energía más limpias y ecológicas.<br><br>Para comparar la combinación de combustibles (es decir, la combinación de recursos) y las tasas de emisión de aire de la electricidad en su región con el promedio nacional y determinar las emisiones de aire derivadas del consumo de electricidad en su hogar o empresa, seleccione la subregión correspondiente de eGRID o ingrese su código postal para determinar la subregión correspondiente de eGRID.",
    "linkToEgrid": "base de datos eGRID",
    "pointToEgrid": "El Analizador de consumo de energía no brinda información sobre los atributos ambientales de la energía eléctrica generada por empresas individuales. Para obtener información de empresas específicas, acceda a la {0} de la EPA. (En inglés).",
    "ariaLabels": {
      "opensNewWin": "abre una nueva ventana"
    }
  }
}
</i18n>
<template>
  <div id="appDescription">
    <p v-html="$t('description')"></p>
    <i18n path="pointToEgrid" tag="p" for="linkToEgrid">
      <a
        href="https://epa.gov/egrid"
        target="_blank"
        v-bind:aria-label="$t('ariaLabels.opensNewWin')"
        >{{ $t("linkToEgrid") }}</a
      >
    </i18n>
  </div>
</template>
