<template>
  <div id="appDescription">
    <p>In the United States, electricity is generated in many different ways, with a wide variation in environmental impact. Electricity generation from the combustion of fossil fuels contributes toward unhealthy air quality, acid rain, and global climate change.</p>
    <p>Many electricity customers can choose their provider of electricity or can purchase green power from their utility. In fact, you might now have the option of choosing cleaner, more environmentally-friendly sources of energy.</p>
    <p>To compare the fuel mix (i.e., resource mix) and air emission rates of the electricity in your region to the national average and to determine the air emissions that result from electricity use in your home or business, either select the appropriate eGRID subregion or enter your ZIP code to determine the appropriate eGRID subregion.</p>
    <p>
      Power Profiler does not provide information about the environmental attributes of electric power generated by individual companies. For company-specific information, access EPA's
      <a
        href="/energy/emissions-generation-resource-integrated-database-egrid"
        target="_blank"
        aria-label="Opens new window"
      >eGRID database</a>.
    </p>
  </div>
</template>
